# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(111114)
$foreground = rgb(D0D6E8)
$color0 = rgb(39393C)
$color1 = rgb(070417)
$color2 = rgb(070417)
$color3 = rgb(16167C)
$color4 = rgb(8D1C2B)
$color5 = rgb(731CAC)
$color6 = rgb(253C8E)
$color7 = rgb(B4BCD6)
$color8 = rgb(7E8395)
$color9 = rgb(09061F)
$color10 = rgb(09061F)
$color11 = rgb(1E1EA6)
$color12 = rgb(BC2539)
$color13 = rgb(9925E5)
$color14 = rgb(3150BD)
$color15 = rgb(B4BCD6)
