# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F1F1F1
background         #252525
cursor             #AAAAAA

active_tab_foreground     #252525
active_tab_background     #F1F1F1
inactive_tab_foreground   #F1F1F1
inactive_tab_background   #252525

active_border_color   #F1F1F1
inactive_border_color #252525
bell_border_color     #592424

color0      #515151
color1		#592424
color2		#732E2E
color3		#783030
color4		#8F3939
color5		#8D3838
color6		#A24141
color7		#E3E3E3
color8		#9F9F9F
color9		#642828
color10		#863636
color11		#8D3939
color12		#933B3B
color13		#A24141
color14		#D85656
color15		#E3E3E3
